### ISSUE TITLE
No 1.5 release

### ISSUE THREAD

**Issue by github12101** [RimWorld-CCL-Reborn/AlienRaces#109]
Hi, in Releases page, latest version published is 1.2 from 2020.
I can't download the files for your mod, unless I do git clone or something?
Can you release 1.5 version please? Thanks.

**Comment by github12101** [comment]
Yeah I had to do git clone to obtain the files, that sorted it...

**Comment by erdelf** [comment]
there's also a download button.. right below the clone address

**Comment by erdelf** [comment]
![image](https://github.com/user-attachments/assets/e3881bda-5223-4efb-854b-33b3812456fd)

**Comment by github12101** [comment]
Got it, thank you!
