### ISSUE TITLE
Way fewer colonies when gender frequency is set to 100% male

### ISSUE THREAD

**Issue by mycroftjr** [RimWorld-CCL-Reborn/AlienRaces#111]
When you change gender frequency to 100% male with something like [Custom Pawn Generation](https://github.com/Llyme/RW_CustomPawnGeneration), way fewer colonies spawn on any world, probably because of a large number of pawns failing generation after 120 attempts.
100% female seems to work fine.

Sibling issue: https://github.com/Llyme/RW_CustomPawnGeneration/issues/14

**Comment by erdelf** [comment]
discussed at sibling issue.
