### ISSUE TITLE
Offset BodyAddon

### ISSUE THREAD

**Issue by alexroeber** [RimWorld-CCL-Reborn/AlienRaces#12]
The offset of body addons was changed, from front/back/side to north/east/south/west. I have no idea which direction is actually meant and the wiki is not adjusted. Please fix that?

**Comment by erdelf** [comment]
Oh yeah, wiki isn't adjusted.. will fix that.
In general, it was changed to go along with the vanilla change of directions in graphics. It is the view direction, so front is south, back is north etc.

**Comment by alexroeber** [comment]
First of all: Thanks a lot, that helped immensely, but some things aren't clear: I changed front->south, back->north, side->east and added west inside the xml. Then I renamed every head file without adding west and did the same to my body addon textures. Heads worked just fine, body addons were invisible from both sides. Changed the east->west in the filenames and everything worked.
So why do I only need east for the head and only west for the body addon textures? Also, please change the wiki for the graphic paths, too.

**Comment by erdelf** [comment]
only needing east is the default because it was the old "side". It is a possibility to use west if something needs a different graphic/offset. It would be news for me that you would only require west for the body addons, especially as these use the same method as the normal Graphics.

**Comment by alexroeber** [comment]
Well, I dunno...

**Comment by alexroeber** [comment]
My heads are all _east, _north and _south, which works and my addons are all _north, _south and _west which works for both sides, which was not the case with _east, _north and _south.
