### ISSUE TITLE
HairTags are not respected for refugee event

### ISSUE THREAD

**Issue by Owlchemist** [RimWorld-CCL-Reborn/AlienRaces#22]
Hello - I am the author of the Lizardmen mod on steam and a user reported a problem I was able to reproduce. When a refugee is spawned (the event where you get a message to offer safety, and then they are chased by raiders), they appear to pull hair from any hair in the game, alien or not. So in my case, I'd have humans with lizard frills.

Upon further investigation, I tested this out with other alien race mods from other authors and had the same problem (for example the Bettlemen mod).

This was done with just the framework + race mod running, and a couple helper mods like hugs lib, jesctools, and mod manager.

The hair tags seem to otherwise be respected elsewhere in the game. Maybe it has something to do with the SpaceRefugee kindef. That's the only common link I could find between the pawns having this problem.

To reproduce, start a crashlanded scenario game and then use dev mode to start making a bunch of refugee events one after the next. Eventually you'll get a human with not-so-human hair.

EDIT: Also it would appear that only vanilla races seem to have this problem. For example, lizardmen refugees always have the correct "hair".

**Comment by erdelf** [comment]
refugees by default pick a random faction to pick hair from. There is the chance to hit an alien faction, causing that issue. Alien races usually have it in their race def what hair is allowed for them which is overwriting that.

It is worth a thought to change the vanilla behavior there.

**Comment by Owlchemist** [comment]
Ah, thank you for the prompt explanation. I'll just leave a "known issues" footnote on my mod's page for now then.
