### ISSUE TITLE
Research screen shows restricted racial research

### ISSUE THREAD

**Issue by Owlchemist** [RimWorld-CCL-Reborn/AlienRaces#23]
I reported this in the comments on the 11th. I figured I may as well post it through proper channels here so it didn't get lost, as I am vested in knowing how it turns out since I use this feature in one of my published mods.

To reiterate, the problem appears to be that racial research appears to be working on a functional level, but not a UI level. I can set it so that only a certain race can actually research something, but if you were to startup a colony with some other race, like humans, they can still see the research options on their research screen and start it up. But they will not be able to able to actually work on it (contribute points).

Tested with a minimal mod configured and rather easy to reproduce. Can be seen in the wild with the Lizardmen mod on steam.

**Comment by dninemfive** [comment]
Can confirm this issue, with the further observation that mods which alter the research screen (e.g. ResearchPal) allow researching these techs.
