### ISSUE TITLE
malformed version string? about.xml is deprecated

### ISSUE THREAD

**Issue by eksynn** [RimWorld-CCL-Reborn/AlienRaces#30]
Malformed (correct format is Major.Minor) version string on mod Humanoid Alien Races 2.0 from erdelf "1.0.0" - parsed as "1.0"
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

<targetVersion> in mod About.xml is deprecated! Use <supportedVersions> tag instead. (example: <supportedVersions><li>1.0</li></supportedVersions>)
[output_log.txt](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/4228918/output_log.txt)

**Comment by erdelf** [comment]
that is definitely an outdated version you have there

**Comment by eksynn** [comment]
but i downloaded the latest 1.0 version on here - where can i get the most updated one then? (not on steam)

edit: i should clarify, i don't own the game on steam, so i can't have 1.1

**Comment by erdelf** [comment]
I just checked, the latest 1.0 release does in fact have the correct version.

https://github.com/RimWorld-CCL-Reborn/AlienRaces/releases/tag/1.0_v2

**Comment by eksynn** [comment]
very weird.. that's the same version i downloaded before
regardless, i'll download it again and test it out

... now if only my game didn't take 20 ~ 30 minutes to load lol
thank you for your time ^^
