### ISSUE TITLE
AddHumanlikeOrdersPostfix only checks single matching item in cell (Deep Storage compatibility)

### ISSUE THREAD

**Issue by lilwhitemouse** [RimWorld-CCL-Reborn/AlienRaces#31]
Deep Storage (https://github.com/lilwhitemouse/RimWorld-LWM.DeepStorage) has storage buildings that allow more than one item to be in a cell.  This means, for example, that a player can have multiple dusters in one cell.  If a race (e.g., Dragonian) cannot use duster, no menu options should be available.  However, some are:  https://ludeon.com/forums/index.php?topic=47707.msg471015#msg471015

AddHumanlikeOrdersPostfix (HarmonyPatches.cs) checks several times for FirstOrDefault(...).  If the code were to check:

    foreach (Thing drugs in c.GetThingList(map: pawn.Map).FindAll(predicate: t => t?.TryGetComp<CompDrug>() != null) {
      // do drug logic
      //build list of FloatMenuOptions that should be disabled
    }
    // disable the list of FloatMenuOptions
    // ....
    foreach (ThingWithComps equipment  / *etc */) {
      // build another list of FloatMenuOptions to be disabled
    }
    //disable, etc

this would solve the problem.  I will also check and see if load order will make a difference.

**Comment by erdelf** [comment]
entirely fair. Thank you.

**Comment by lilwhitemouse** [comment]
Actually, I am not sure why this doesn't work as is, with different mod order, but player reports changing mod order does not help.  If you could make that change, at least one person would be happier.

Thanks
