### ISSUE TITLE
switching parentname to "BasePawn" causes errors

### ISSUE THREAD

**Issue by mc-oofy** [RimWorld-CCL-Reborn/AlienRaces#34]
it opens the incompatible screen on start and errors stuff
HumanRace is not an option for me because it messes stuff up with my race
[Player.log](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/4597372/Player.log)
`<AlienRace.ThingDef_AlienRace ParentName="BasePawn">`

```
<PawnKindDef ParentName="BasePlayerPawnKind">
		<defName>ArachnoidMegaSpiderKind</defName>
		<label>Arachnoid</label>
		<defaultFactionType>PlayerColony</defaultFactionType>
		<race>MegaspiderHuman</race>
	</PawnKindDef>
```

**Comment by erdelf** [comment]
you didn't define vanilla race stats.

**Comment by mc-oofy** [comment]
@erdelf how does that give the errors in the player log and im gonna try doing what you suggested

**Comment by erdelf** [comment]
Your issue is that vanilla looks for a lot of vanilla stats like definitions for the meat.

**Comment by mc-oofy** [comment]
@erdelf does not fix the issue

**Comment by erdelf** [comment]
unless you give your xml, I can't help your specific issue

**Comment by mc-oofy** [comment]
[race.txt](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/4597755/race.txt)
changed the xml file into a txt file so github accepts it

**Comment by erdelf** [comment]
you didn't add vanilla race fields, please refer to vanilla races for that.

**Comment by mc-oofy** [comment]
what fields

**Comment by erdelf** [comment]
under the race tag.
I'll also close this, as it's clear your issue is not with the framework, but inexperience with vanilla races.
