### ISSUE TITLE
Issue with mods: other mods depending on AlienRaces do not seem to know it's already there.

### ISSUE THREAD

**Issue by s507** [RimWorld-CCL-Reborn/AlienRaces#37]
donno if it's a mod manager issue or not, but it's very annoying.
![RimWorldWin64_KRrhu1hhRS](https://user-images.githubusercontent.com/59029502/87878716-a1130880-c9ee-11ea-9db7-1a8e87bf80a0.png)

**Comment by erdelf** [comment]
That's just a minor issue related to mod manager trying to read their own system and vanilla's half assed system.
