### ISSUE TITLE
Rimworld 1.2: Errors for AlienTraitEntry

### ISSUE THREAD

**Issue by OrionFive** [RimWorld-CCL-Reborn/AlienRaces#38]
When starting up RimWorld in 1.2, I'm now getting various AlienRaces related errors. I didn't have these yesterday.

https://gist.github.com/cc91ca54666be7bd3377d304ee2b5e3b

**Comment by erdelf** [comment]
Correct, 1.2 is a version update for RimWorld, with the opportunity to revamp some outdated tags. Let the Race Modders update their specific races, the wiki is updated and on the discord I already discussed with them what needs changing.

**Comment by OrionFive** [comment]
Ah, I see. Thanks for the info.
