### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by Canute00** [RimWorld-CCL-Reborn/AlienRaces#4]
Since how many version are 
<name>Humanoid Alien Races 2.0</name>
still the same ?
Don't you think this could be updated too, special since this part is displayed at the error log
"Humanoid Alien Races 2.0: 0Harmony(1.0.9.1), AlienRace(1.0.0.0), _harmonycheck(1.0.0.0)"

**Comment by erdelf** [comment]
Does it really matter tough ? It's just to say it is a completely new version compared to the one before the rewrite.

**Comment by erdelf** [comment]
you know what... if I remember it at some point.. I'll change the number.
