### ISSUE TITLE
Customizable thoughts not working?

### ISSUE THREAD

**Issue by rhadamant** [RimWorld-CCL-Reborn/AlienRaces#42]
I've created a <butcherThoughtGeneral> inside the  <thoughtSettings> that is supposed to setup for butchery, but it does not work. 

Here is the relevant code

[Thoughts_Memory_Misc.txt](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/5205311/Thoughts_Memory_Misc.txt)
[KenshiSkeletonRace.txt](https://github.com/RimWorld-CCL-Reborn/AlienRaces/files/5205313/KenshiSkeletonRace.txt)

I had to paste the xml into txt files to upload.

Additionally it does not look like replacerList is working either (trying to change the observed corpse thought)

**Comment by erdelf** [comment]
And what exactly doesn't work?
What happens ?

**Comment by rhadamant** [comment]
The vanilla thoughts happen, the modded thoughts are as if they don't exist. It is possible I implemented it wrong, if you could provide an example of a working <butcherThoughtGeneral> and <replacerList> I can double check myself for errors

**Comment by erdelf** [comment]
Apologies for the late answer. I did a quick check with your thoughts and your butcher config on a different race and it worked fine.

**Comment by rhadamant** [comment]
Oh, very odd, I'll keep troubleshooting!

**Comment by rhadamant** [comment]
I've tried to use my <thoughtSettings> in another race mod to see if it is some setting elsewhere I have wrong, but inserting the same snippet of code into other races failed to work too. Could you send or link me an example where it works so I can maybe reverse engineer where I went wrong?

**Comment by rhadamant** [comment]
How would I go about making a normal human feel about butchering an alien species? I've come to understand that the <butcherThoughtGeneral> affects how an alien species feels when one butchers one of their own, but not how another species feels about butchering them.

I would like default humans to have a custom thought about butchering an alien species.

**Comment by erdelf** [comment]
You would have to patch the thought settings of humans and add a `butcherThoughtSpecific` entry

**Comment by rhadamant** [comment]
Is there a way to run a PatchOperation to make the vanilla humans humanoid aliens ?

**Comment by erdelf** [comment]
They already are if you use this mod.
[Relevant Patch](https://github.com/RimWorld-CCL-Reborn/AlienRaces/blob/master/1.2/Patches/HumansAreAliensToo.xml)

**Comment by rhadamant** [comment]
Alright perfect, thanks erdelf!
