### ISSUE TITLE
Feature Request - forced hediff in general settings

### ISSUE THREAD

**Issue by rwilkin** [RimWorld-CCL-Reborn/AlienRaces#45]
Is it possible to have a forcedRaceHediff as part of the general settings in the race? 
So every pawn of that race gets the hediff.

**Comment by erdelf** [comment]
You can do that via the races hediffgiver.

**Comment by rwilkin** [comment]
I might be missing it - but I can't find the hediffgiver on the wiki

**Comment by goudaQuiche** [comment]
Come on the HAR discord, we will lead you. HediffGiver is a vanilla feature, that's why the wiki does not need to document it.
