### ISSUE TITLE
unable to create new world

### ISSUE THREAD

**Issue by donoya** [RimWorld-CCL-Reborn/AlienRaces#5]
https://gist.github.com/f22944534523791fa036c33ed6e9dffd

**Comment by erdelf** [comment]
For the next time I would advise saying something.

In general, try validating files, your copy of vanilla is broken.
Otherwise.. you are missing some dependencies for other mods, like JecsTools and FrontierDevelopment.

**Comment by donoya** [comment]
Validating didn't do anything. Steam said all files validated successfully.

**Comment by erdelf** [comment]
It can't find one of the base functions of the game... and it works for everybody else.. so I'm pretty sure your files are broken. Try deleting the Assembly-Csharp (or something like that) in the Rimworld_Data/Managed folder and then revalidate.

**Comment by donoya** [comment]
That seems to have fixed it. Though now there's another error where the world screen is completely black. I can't seem to identify which mod/mods are at fault here. Here's the new log: https://gist.github.com/529da1788b071541a7d65b940dbc827a 
Sorry for bothering you with this.

**Comment by erdelf** [comment]
uhm... same error.. different position... but what the heck is up with your vanilla... it broke two times.. in different locations. Don't know what to tell you... the only fix I'm aware of is... again deleting the assembly-csharp file. if that doesn't work.. I have no idea honestly.

**Comment by donoya** [comment]
I don't think it's my vanilla. After removing all mods from the load order, it seems to work fine, despite throwing errors each time I do something in the creating new colony area. So I'll try re-adding mods one by one until I discover the culprit. Thanks for all the help. I'll let you know if I find it.

**Comment by erdelf** [comment]
oh it's alienrace.. and it is vanilla beeing damaged.. problem is... vanilla only requires a certain amount of structural integrity to run... these 2 particular lines you errored out on requires it to be completely intact, with information that vanilla itself doesn't need.

**Comment by donoya** [comment]
I noticed one of the errors is referring to wm reuse pods, which I don't have. Could it be something in the appdata folder? I noticed steam doesn't seem to do anything with things in that folder.

**Comment by erdelf** [comment]
oh that is only about that mod using incorrect tags for the mod data, that is required for the game to read it.. it is just outdated, you don't need it activated. 

I mean.. in general I've told you about some missing dependencies already.
Also.. some mod you have that changes terrains horribly failed in it's job.
And well.. you have at least one (I think more like.. twenty) mods that are still a17 (or at least weren't properly updated to b18)

**Comment by donoya** [comment]
So far, I've found that the water power mod is causing an error immediately, so I'm disabling it to see if that works.

**Comment by donoya** [comment]
Still no luck. Also, I noticed that I couldn't select the asari or jaffa races despite having those in my modlist.

**Comment by donoya** [comment]
Found it! It seems to be an issue with either glittertech, or rimsenal plus maybe one or two other mods.
