### ISSUE TITLE
Latest Update Breaks Game

### ISSUE THREAD

**Issue by MichaelSteer** [RimWorld-CCL-Reborn/AlienRaces#6]
Myself and many others (see the steam workshop comments [here](https://steamcommunity.com/workshop/filedetails/?id=839005762)) game's have broken with the latest update. The issue seems to stem from harmony.

A copy of my log file can be found [here](https://pastebin.com/6c9Um8Mz) if that helps.

I would love to see this fixed in the near future as your mod is the basis of multiple mods used in a colony I have sank over 50 hours into.

Thanks for the support and keep up the great work!

**Comment by erdelf** [comment]
huh, somehow I never saw that. But well, I should've fixed that back then.
