### ISSUE TITLE
slavery/eating precepts don't override some vanilla thoughts

### ISSUE THREAD

**Issue by lag42** [RimWorld-CCL-Reborn/AlienRaces#69]
alien slavery, honorable or acceptable doesn't override slaves in colony or enslaved prisoner thoughts

with regular slavery honorable and alien slavery abhorrent/disapproved/horrible you still get the mood buff

eating aliens preferred/required also doesn't override i butchered humanlike/we butchered humanlike from cannibalism abhorrent/horrible/disapproved

the butchered alien thought from eating aliens disapproved/abhorrent just doesn't seem to appear under any circumstances

apologies if any of this was intentional, if so i would still like to turn this into a feature request for a config option to override these(if it's not too much trouble to patch)

[log for slavery=abhorrent/alien slavery=honorable](https://gist.github.com/HugsLibRecordKeeper/ec4467ea259bc331d05e75615fa3ee86)

[log for cannibalism=horrible/eating aliens=preferred](https://gist.github.com/HugsLibRecordKeeper/e15cce281c01fe7d356fd194da9e9ea2)

[log for cannibalism=disapproved/eating aliens=abhorrent](https://gist.github.com/3faf8679f19d491a8f23597c30ee8fb5)

[RimRaces - Caerulean Race](https://steamcommunity.com/sharedfiles/filedetails/?id=2691448639) used as other race for testing, [fantasy goblins updated](https://steamcommunity.com/sharedfiles/filedetails/?id=2011680079) was also present for the butcher tests to check if leather type made a difference, as well as hugslib and harmony being enabled for ease of uploading log, load order is as follows:

1: harmony
2: core
3: royalty
4: ideology
5: hugslib
6: humanoid alien races
7: rimraces caerulean race
8: fantasy goblins

**Comment by ArixZajicek** [comment]
I'd like to follow up with this if anyone has more info on it. It seems that the eating/butchering aliens preferred/disapproved etc. are no longer an issue, but the "No Alien Slaves" with alien slavery honorable debuff still appears. I'm looking into it to see if I can help fix though!

**Comment by ArixZajicek** [comment]
Just added some debug output to HAR and it looks like the mod author of a race had set `<immuneToXenophobia>` to true when it doesn't really make sense to. There is no issue here with HAR, sorry for posting on an old issue thinking it was still present.
