### ISSUE TITLE
Something something, update, missing method

### ISSUE THREAD

**Issue by Syrchalis** [RimWorld-CCL-Reborn/AlienRaces#7]
When butchering anything:

JobDriver threw exception in initAction for pawn Reisa driver=JobDriver_DoBill (toilIndex=13) driver.job=(DoBill (Job_141377) A=Thing_TableButcher84901 B=Thing_Corpse_Hare133508 C=(107, 0, 116)) lastJobGiver=RimWorld.JobGiver_Work
System.MissingMethodException: Method not found: 'RimWorld.TaleRecorder.RecordTale'.
at AlienRace.HarmonyPatches.ButcherProductsPrefix (Verse.Pawn,single,System.Collections.Generic.IEnumerable`1<Verse.Thing>&,Verse.Corpse) <IL 0x00028, 0x000ac>

HarmonyPatches.cs line 1587

**Comment by erdelf** [comment]
I'm gonna need a little more info on that. What rimworld version are you on ?
What alien race version are you on ?
Where is the full log.
