### ISSUE TITLE
Pawn graphics are cut off

### ISSUE THREAD

**Issue by accrrsd** [RimWorld-CCL-Reborn/AlienRaces#76]
On new versions of RimWorld, if you set the custom Draw Size to large values (5-10), the pawn graphics will be cut off, and if this does not happen, you can put on large armor (for example, phoenix armor) and notice it.

I checked the same mod on versions 1.1 (works well), 1.3 (cropped).

To reproduce, you can take absolutely any race, even standard human bodies without a graphical path and increase the size.

**Comment by PrincessOfEvil** [comment]
`atlasScale` and `borderScale` are the fix for that.
`atlasScale` changes the resolution of the pawn, while `borderScale` increases the actual drawn size of the pawn.
It is recommended to use powers of 2 there, and not go bigger than you need them, as it drains VRAM rapidly.

**Comment by erdelf** [comment]
Thank your Princess. To give additional context... that is a result of the vanilla game caching pawns in 1.3.
The caching only takes a certain area into account and if you go outside that.. well.
