### ISSUE TITLE
Exception from ButcherProductsPrefix preventing butchering

### ISSUE THREAD

**Issue by isacmms** [RimWorld-CCL-Reborn/AlienRaces#8]
It seems after Rimworld 1.0.1982 update some things were changed with animals. And now, somehow, the method RimWorld.TaleRecorder.RecordTale can't be found when AlienRace.HarmonyPatches.ButcherProductsPrefix runs.

After the bill is finished and the exception is raised, the butcher pawn stands still for a couple seconds and then try again (nothing happens with the corpse, it just remains on top of the table).

The method (RecordTale) still exists with the same signature tho.

LOG
https://git.io/fNDDc

**Comment by erdelf** [comment]
Please use the latest release
