### ISSUE TITLE
Starting colonist Randomize button does not factor AlienRace.PawnKindSettings.startingColonists in v1.4

### ISSUE THREAD

**Issue by SineSwiper** [RimWorld-CCL-Reborn/AlienRaces#87]
RimWorld v1.4 changes the way pawns are randomized by implementing more caching in `StartingPawnUtility`.  This caching is interfering with `AlienRace.PawnKindSettings.startingColonists` settings when the Randomize button is hit.  The initial set of pawns on the left-side will honor HAR2 settings, but any further Randomize hits will not.

**Comment by erdelf** [comment]
Maybe test that one a bit more, because it seems you are misinterpreting a small data set. The caching is merely preventing a different race from being rolled.

**Comment by SineSwiper** [comment]
> The caching is merely preventing a different race from being rolled.

Isn't that the point of a `startingColonists` setting in an alien race framework?

**Comment by erdelf** [comment]
the point is not specifically to spam the reroll button, no. It's to influence the generation of pawns.
That rerolling doesn't change the race after the first reroll is the caching, but it is just simply soft-rerolling whatever race is there. That may be from startingColonists or may be the actual base member of the faction.

**Comment by erdelf** [comment]
well, for better or worse https://github.com/erdelf/AlienRaces/commit/dcaede1f7082235788c8440499897db06562a6fb
