### ISSUE TITLE
Caravan reduces framerate to 1 fps because of AlienRace mod. 

### ISSUE THREAD

**Issue by XeonPhobia** [RimWorld-CCL-Reborn/AlienRaces#91]
AlienRace encountered an error processing food
Pawn: dromedary 1 | Dromedary
Food: Rawsugarcane | Rawsugarcane | Core SK
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) AlienRace.HarmonyPatches.AlienRace.HarmonyPatches.ThoughtsFromIngestingPostfix_Patch0(Verse.Pawn,Verse.Thing,Verse.ThingDef,System.Collections.Generic.List`1<RimWorld.FoodUtility/ThoughtFromIngesting>&)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
(wrapper dynamic-method) AlienRace.HarmonyPatches:AlienRace.HarmonyPatches.ThoughtsFromIngestingPostfix_Patch0 (Verse.Pawn,Verse.Thing,Verse.ThingDef,System.Collections.Generic.List`1<RimWorld.FoodUtility/ThoughtFromIngesting>&)
(wrapper dynamic-method) RimWorld.FoodUtility:RimWorld.FoodUtility.ThoughtsFromIngesting_Patch1 (Verse.Pawn,Verse.Thing,Verse.ThingDef)
RimWorld.FoodUtility:WillGiveNegativeThoughts (Verse.Thing,Verse.Pawn)
(wrapper dynamic-method) RimWorld.Dialog_FormCaravan:RimWorld.Dialog_FormCaravan.GetFoodScore_Patch0 (RimWorld.Dialog_FormCaravan,Verse.Pawn,Verse.Thing,System.Collections.Generic.List`1<Verse.Pair`2<int, int>>)
RimWorld.Dialog_FormCaravan:BestFoodItemFor (Verse.Pawn,System.Collections.Generic.IEnumerable`1<RimWorld.TransferableOneWay>,System.Collections.Generic.List`1<Verse.Pair`2<int, int>>)
RimWorld.Dialog_FormCaravan:SelectApproximateBestTravelSupplies ()
RimWorld.Dialog_FormCaravan:CountToTransferChanged ()
RimWorld.Dialog_FormCaravan:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

AlienRace encountered an error processing food
Pawn: dromedary 1 | Dromedary
Food: Pemmican | Pemmican | Core SK
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) AlienRace.HarmonyPatches.AlienRace.HarmonyPatches.ThoughtsFromIngestingPostfix_Patch0(Verse.Pawn,Verse.Thing,Verse.ThingDef,System.Collections.Generic.List`1<RimWorld.FoodUtility/ThoughtFromIngesting>&)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch4 (string)
(wrapper dynamic-method) AlienRace.HarmonyPatches:AlienRace.HarmonyPatches.ThoughtsFromIngestingPostfix_Patch0 (Verse.Pawn,Verse.Thing,Verse.ThingDef,System.Collections.Generic.List`1<RimWorld.FoodUtility/ThoughtFromIngesting>&)
(wrapper dynamic-method) RimWorld.FoodUtility:RimWorld.FoodUtility.ThoughtsFromIngesting_Patch1 (Verse.Pawn,Verse.Thing,Verse.ThingDef)
RimWorld.FoodUtility:WillGiveNegativeThoughts (Verse.Thing,Verse.Pawn)
(wrapper dynamic-method) RimWorld.Dialog_FormCaravan:RimWorld.Dialog_FormCaravan.GetFoodScore_Patch0 (RimWorld.Dialog_FormCaravan,Verse.Pawn,Verse.Thing,System.Collections.Generic.List`1<Verse.Pair`2<int, int>>)
RimWorld.Dialog_FormCaravan:BestFoodItemFor (Verse.Pawn,System.Collections.Generic.IEnumerable`1<RimWorld.TransferableOneWay>,System.Collections.Generic.List`1<Verse.Pair`2<int, int>>)
RimWorld.Dialog_FormCaravan:SelectApproximateBestTravelSupplies ()
RimWorld.Dialog_FormCaravan:CountToTransferChanged ()
RimWorld.Dialog_FormCaravan:DoWindowContents (UnityEngine.Rect)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

**Comment by erdelf** [comment]
for one, full log next time.
But also, this seems like just an old version of the framework? With a full log I could verify
