### ISSUE TITLE
Can't find 1.4 update

### ISSUE THREAD

**Issue by Wedaphillips** [RimWorld-CCL-Reborn/AlienRaces#92]
The latest update file posted of this mod is 1.2. Any help is appreciated in helping me find 1.4 update. Thanks

**Comment by erdelf** [comment]
the latest release is 1.2, you can always just.. press the green code button on the main page to download the current state.

**Comment by Wedaphillips** [comment]
Ok. I was hoping there was a 1.3 or 1.4 version like I saw on steam.  I
really appreciate you taking the time to respond.
Thanks

**Comment by erdelf** [comment]
the current 1.4 version is downloadable as I explained it. Green code button

**Comment by Wedaphillips** [comment]
Awesome, thanks! I was looking under the release spot on the right hand
side.
