### ISSUE TITLE
Backer pawns with unique custom backstories never appear

### ISSUE THREAD

**Issue by Lade24** [RimWorld-CCL-Reborn/AlienRaces#96]
The backer pawns with unique custom backstories from this list never appear in the game: https://www.reddit.com/r/RimWorld/comments/vhj088/list_of_all_backers_submitted_unique_pawns/

I added some of those names in the "Preferred 'Name in Game' Characters" game option and tested it using the mod Prepare Moderately. Without Humanoid Alien Races active they appeared consistently in the first 100-1000 rerolls but with it active they never show up, even after 10000+ rerolls

The backer pawns that only have a custom name and always get a random backstory show up normally even with Humanoid Alien Races active

**Comment by erdelf** [comment]
if the pawn bios show up is up to the race modders

**Comment by Lade24** [comment]
Is it intended that they never show up even for normal humans?
